# Generated by Django 4.1.1 on 2023-04-25 18:19

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "appointment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="loginForm",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "report_id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("t3", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tt4", models.DecimalField(decimal_places=2, max_digits=5)),
                ("t4u", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fti", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sex", models.IntegerField()),
                ("sick", models.IntegerField()),
                ("pregnant", models.IntegerField()),
                ("thyroid_surgery", models.IntegerField()),
                ("goitre", models.IntegerField()),
                ("tumor", models.IntegerField()),
                ("category", models.CharField(max_length=20, null=True)),
                (
                    "upload_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 4, 25, 23, 49, 33, 890957),
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "patients",},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=256)),
                (
                    "image",
                    models.ImageField(default="default.png", upload_to="profile_pics"),
                ),
                ("address", models.CharField(blank=True, max_length=256)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "last_upd",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 4, 25, 23, 49, 33, 890957),
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "userprofiles",},
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialty", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "doctor",},
        ),
    ]
