# Generated by Django 4.1.1 on 2023-04-25 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_upd",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 4, 25, 23, 49, 51, 11439)
            ),
        ),
        migrations.AlterField(
            model_name="userreport",
            name="upload_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 4, 25, 23, 49, 51, 11439)
            ),
        ),
    ]
